<a href="https://colab.research.google.com/github/KARINAgoncalvesSOARES/Pandas/blob/main/a_melhor_forma_de_filtrar_dados_numericos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Python PANDAS - A melhor forma de filtrar dados numéricos](https://www.youtube.com/watch?v=FWQ-o54wuPM&list=PLEdfCNsWt0gxURVswsV_STMrCo_n7rD5M&index=3&ab_channel=ProgramePython)

In [ ]:
import pandas as pd

In [ ]:
dados = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]

In [ ]:
df = pd.DataFrame(data = dados, columns=['col1', 'col2', 'col3'])

In [ ]:
df

   col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9
3    10    11    12

In [ ]:
#Passando uma condição
#Eu tô pedindo para imprimeir apenas os valores da col1 que são maiores que 6

df[df['col1'] > 6]

   col1  col2  col3
2     7     8     9
3    10    11    12

In [ ]:
#Condição |(ou) e &(e)
#Quando eu quero passar duas condições para o df, é necessário que eu coloque cada uma delas em um parenteses para que não haja duplicidade.

df[(df['col1'] > 6) | (df['col2'] > 6)]

   col1  col2  col3
2     7     8     9
3    10    11    12

In [ ]:
df[(df['col1'] < 6) & (df['col2'] < 6)]

   col1  col2  col3
0     1     2     3
1     4     5     6

In [ ]:
# eu quero o(s) número(s) que estão entredois valores. [].between()
# between significa entre 

df[df['col1'].between(1,5)]

   col1  col2  col3
0     1     2     3
1     4     5     6

In [ ]:
# Retorna as linhas em que a soma é maior que o valor indicado

df[df.sum(axis=1) ==15]

   col1  col2  col3
1     4     5     6

In [ ]:
# Filtrando as linhas em que o valor máximo.

df[df.max(axis=1) < 12]

   col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9