<a href="https://colab.research.google.com/github/KARINAgoncalvesSOARES/Pandas/blob/main/como_filtrar_dados_com_loc__e_iloc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # <h2 align="center"> Usando loc and iloc
 
 Data Scientist Jr.: Karina Gonçalves Soares
 

Link de estudo:
* [Python PANDAS - Como filtrar dados com LOC e ILOC
](https://www.youtube.com/watch?v=5BJtFsCbICM&list=PLEdfCNsWt0gxURVswsV_STMrCo_n7rD5M&index=2&ab_channel=ProgramePython)

Esses objetos tem como principal função filtrar dados numéricos.

In [ ]:
import pandas  as pd

In [ ]:
dados = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]
df = pd.DataFrame(dados, 
                  index=['lin1','lin2','lin3','lin4'],
                  columns=['col1','col2','col3'])

In [ ]:
df

      col1  col2  col3
lin1     1     2     3
lin2     4     5     6
lin3     7     8     9
lin4    10    11    12

In [ ]:

# O .loc[] faz filtragem a partir do nome do meu índice:
# df.loc[] - Series
df.loc['lin1']

col1    1
col2    2
col3    3
Name: lin1, dtype: int64

In [ ]:
# df.loc[[]] - DataFrame 
df.loc[['lin1']]

      col1  col2  col3
lin1     1     2     3

In [ ]:
# se eu quiser adicionar mais de uma linha é só eu adicionar
df.loc[['lin1', 'lin3']]

      col1  col2  col3
lin1     1     2     3
lin3     7     8     9

In [ ]:
# O .iloc[[]] permite fazer esse filtro atravéz da posição da linha do meu Dataframe atravéz da indexação do python.
#que como sabemos começa a partir do 0(zero)

df.iloc[[0,3]]

      col1  col2  col3
lin1     1     2     3
lin4    10    11    12

In [ ]:
# O .iloc permite com que a gente trabalhe com algo semelhante as listas do Python
#por exemplo:

df.iloc[0:3]

      col1  col2  col3
lin1     1     2     3
lin2     4     5     6
lin3     7     8     9

In [ ]:
# O .iloc funciona da mesma forma ao contrário

df.iloc[1:]

      col1  col2  col3
lin2     4     5     6
lin3     7     8     9
lin4    10    11    12

In [ ]:
# O .loc funciona da mesam forma que o .iloc

df.loc['lin1':'lin3']

      col1  col2  col3
lin1     1     2     3
lin2     4     5     6
lin3     7     8     9

In [ ]:
# Eu também posso fazer filtros mais complexos, como poe ex.:
# vou colocar o df.loc[df['e aqui eu passo uma condição']]

df.loc[df['col1']>2] #Por exemplo o meu próprio df da coluna 1 se maior que 2

      col1  col2  col3
lin2     4     5     6
lin3     7     8     9
lin4    10    11    12

In [ ]:
# E isso pode se estender para qualquer tipo de condição ou até para mais de uma condição
#se eu colocar isso entre parenteses e adicionar o operador ou que é representado pela |(barra verticao) ou &(i comercial)

#df.loc[(condição1) & (condição2)]

df.loc[(df['col1']>2) & (df['col1']<10)]

      col1  col2  col3
lin2     4     5     6
lin3     7     8     9

In [ ]:
# Se eu quiser por exemplo substituir todos os valores da lin1:7

df.iloc[0]=[7,3,0]
df

      col1  col2  col3
lin1     7     3     0
lin2     4     5     6
lin3     7     8     9
lin4    10    11    12

In [ ]:
# Substituindo os valores por valores negativos

df.iloc[2]=-df.iloc[2]
df

      col1  col2  col3
lin1     7     3     0
lin2     4     5     6
lin3    -7    -8    -9
lin4    10    11    12