<a href="https://colab.research.google.com/github/KARINAgoncalvesSOARES/Pandas/blob/main/formatar_casas_decimais_e_numeros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <h2 align="center"> Formatando Casas Decimais e Números

Data Scientist Jr.: Karina Gonçalves Soares

Estudo baseado em:

* [Python PANDAS - Formatar casas decimais e números](https://www.youtube.com/watch?v=pihTC6Z8bgI&list=PLEdfCNsWt0gxURVswsV_STMrCo_n7rD5M&index=7&ab_channel=ProgramePython)

In [ ]:
import pandas as pd 
import numpy as np

In [ ]:
dados = [[111.23548, 478.245784],
         [222.58485, 444.888978],
         [123.456578, 555.585478]]
        
dados1 = [[111.23548e+05, 478.245784e+00],
         [222.58485e+06, 444.888978e+06],
         [123.456578e+06, 555.585478e+05]]

In [ ]:
df = pd.DataFrame(dados,columns=('col1','col2'))
df1 = pd.DataFrame(dados1, columns=('col1','col2'))

In [ ]:
df

         col1        col2
0  111.235480  478.245784
1  222.584850  444.888978
2  123.456578  555.585478

In [ ]:
#df,describe(), passa algumas estatísticas do Data Frame
df.describe()

             col1        col2
count    3.000000    3.000000
mean   152.425636  492.906747
std     61.066155   56.785884
min    111.235480  444.888978
25%    117.346029  461.567381
50%    123.456578  478.245784
75%    173.020714  516.915631
max    222.584850  555.585478

In [ ]:
#pd.set_option('display.precision',2) --> no caso eu estou limitando ou exibindo com precisão as casa decimais
#onde aparecera no f=gráfico apenas a quantidade de casas decimais que eu desejar
#No caso ele aredondou todos os valores para duas casas decimais

pd.set_option('display.precision',2)

In [ ]:
df

     col1    col2
0  111.24  478.25
1  222.58  444.89
2  123.46  555.59

In [ ]:
#Voltando as casas decimais ao normal
pd.reset_option('^display.', silent=True)

In [ ]:
df

         col1        col2
0  111.235480  478.245784
1  222.584850  444.888978
2  123.456578  555.585478

In [ ]:

df1

          col1          col2
0   11123548.0  4.782458e+02
1  222584850.0  4.448890e+08
2  123456578.0  5.555855e+07

In [ ]:
#Retirando valores em notação ciêntifica

pd.set_option('float_format', '{:.3f}'.format)

In [ ]:
df1

           col1          col2
0  11123548.000       478.246
1 222584850.000 444888978.000
2 123456578.000  55558547.800