<a href="https://colab.research.google.com/github/KARINAgoncalvesSOARES/Pandas/blob/main/melhor_forma_de_filtrar_dados_string.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Como filtara strings no pandas:

[Python PANDAS - A melhor forma de filtrar dados string](https://www.youtube.com/watch?v=-1EM45iFe_8&list=PLEdfCNsWt0gxURVswsV_STMrCo_n7rD5M&index=4&ab_channel=ProgramePython)

In [ ]:
import pandas as pd

In [ ]:
dados = [['ola', 'bem', 'vindos'], ['ao','programe', 'python+'],['aula', 'de', 'hoje'], ['filtros', 'pandas', 'python']]

In [ ]:
df = pd.DataFrame(dados, columns=['col1','col2','col3'])
df

      col1      col2     col3
0      ola       bem   vindos
1       ao  programe  python+
2     aula        de     hoje
3  filtros    pandas   python

In [ ]:
#Primeira condição

df[df['col1'] == 'ola']

  col1 col2    col3
0  ola  bem  vindos

In [ ]:
#.isin(), filtra apenas a linha em que está a palavra que for indicada.

df[df['col3'].isin(['python', 'python+'])]

      col1      col2     col3
1       ao  programe  python+
3  filtros    pandas   python

In [ ]:
#str, há uma infinidade  de funções onde podemos a usar(consultar documentação)
#mas aqui nós vamos fazer contagem da quantidade de caracteres que uma string possui e passa uma condição para a impressão:

df[df['col3'].str.len() > 5]

      col1      col2     col3
0      ola       bem   vindos
1       ao  programe  python+
3  filtros    pandas   python

In [ ]:
#.str.contains(), proucura strings no meu data frame que contenham por ex a a sílaba indicada

df[df['col3'].str.contains('os|e|\+')]

   col1      col2     col3
0   ola       bem   vindos
1    ao  programe  python+
2  aula        de     hoje